appName: myhelmapp

namespace: test-argocd

port: 80

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: andrii33/test
  tag: 0.0.1


HookImage:
  name: 360_base_b2b_image_test
  tag: 247c2118cfc64200f33562c0eadbe26540f36acc