apiVersion: batch/v1
kind: Job
metadata:
  generateName: deploy-test-
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: Ignore
spec:
  template:
    spec:
      containers:
      - name: deploy-test-msg
        image: "{{ .Values.HookImage.name }}:{{ .Values.HookImage.tag }}"
        command:
          - "sh"
          - "-c"
          - "./deploy/deploy.sh"
      restartPolicy: Never
  backoffLimit: 2
