apiVersion: batch/v1
kind: Job
metadata:
  generateName: deploy-test-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: Ignore
spec:
  template:
    spec:
      containers:
      - name: deploy-test-msg
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        command:
          - "sh"
          - "-c"
          - "/code/deploy/deploy.sh"
      restartPolicy: Never
  backoffLimit: 2
